name: Auto-fetch data

on:
  schedule:
    - cron: "0 8 * 9-12 2" # Tuesdays, September-December
    - cron: "0 8 * 1 2" # Tuesdays, January
  workflow_dispatch:

jobs:
  update-nfl-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - run: corepack enable
        shell: bash

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Fetch latest NFL data
        run: yarn fetch

      - name: Exit if no changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 1
          fi

      - name: Create PR with gh CLI
        run: |
          BRANCH="update-data-$(date +'%Y-%m-%d')"
          TITLE="Update with latest data as of $(date +'%Y-%m-%d')"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "$TITLE"
          git push origin "$BRANCH"
          gh pr create \
            --title "$TITLE" \
            --body "$TITLE" \
            --head "$BRANCH" \
            --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
